# Default state for all rules
default: true

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md013.md
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md033.md
MD033:
  # Allowed elements
  allowed_elements: ["div", "a", "kbd", "picture", "source", "img"]
